---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg-agent 
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker apt key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name : Add Docker repository
  apt_repository: 
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install latest version of Docker Engine
  apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: latest

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes
