---
# Used only for Debian/Ubuntu
docker_apt_arch: "amd64"
docker_apt_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

# Used only for CentOS/Fedora.
docker_yum_repo_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo"
docker_yum_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"


